### ISSUE TITLE
Unable to start local project on Node v18

### ISSUE THREAD

**Issue by adan-ea** [mikeyaworski/Twitch-Lurker#18]
I wanted to work on this because i love the extension.
But no matter what I try, the app won't launch.
I 
- cloned the `master` branch,
- went to `app`,
- did `npm run build:all`. 
Didn't work, so I did `npm i` then `npm run build:all` got the error below. Then did `npm run build:popup` and got the same error.
![image](https://github.com/mikeyaworski/Twitch-Lurker/assets/57812567/e6c720cb-d8c4-40b4-b5e3-26cceeec109b)

I have Node 18.18.0

**Comment by mikeyaworski** [comment]
This root issue is with react-scripts v4. It breaks on Node v18 because of a bug fix in OpenSSL. To fix, I can upgrade to react-scripts v5, but cra-build-watch is incompatible, which is really useful for local development. Eventually, I'll migrate this project to Vite and avoid this whole mess anyway, so I'm not going to fix this issue directly with CRA.

### Solution

Either use Node v16 (I use https://github.com/nvm-sh/nvm or https://github.com/coreybutler/nvm-windows to switch between Node versions), or apply this commit to your code locally if you want to use Node v18 instead (but don't commit to repo): https://github.com/mikeyaworski/Twitch-Lurker/commit/4541d3404bf46aa420af958b6fb1d51000ef4c9f

**Comment by adan-ea** [comment]
I already have nvm, i'll try that thanks !
